# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 2147483647) do

  create_table "announcements", :force => true do |t|
    t.column "title",       :string
    t.column "description", :text
    t.column "status",      :boolean
  end

  create_table "categories", :force => true do |t|
    t.column "name",       :string
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "contacteds", :force => true do |t|
    t.column "patient_first", :string
    t.column "patient_last",  :string
    t.column "accident_date", :date
    t.column "zip",           :string
    t.column "created_at",    :datetime
    t.column "updated_at",    :datetime
  end

  create_table "db_files", :force => true do |t|
    t.column "data", :binary
  end

  create_table "e_files", :force => true do |t|
    t.column "parent_id",         :integer
    t.column "content_type",      :string
    t.column "filename",          :string
    t.column "size",              :integer
    t.column "user_id",           :integer
    t.column "db_file_id",        :integer
    t.column "status",            :integer,  :default => 0
    t.column "created_at",        :datetime
    t.column "updated_at",        :datetime
    t.column "page_count",        :integer
    t.column "status_code",       :integer
    t.column "status_condition",  :string
    t.column "error_description", :text
    t.column "sent_date",         :date
    t.column "returned_date",     :date
    t.column "grantee_first",     :string
    t.column "grantee_last",      :string
  end

  create_table "insurance_companies", :force => true do |t|
    t.column "name",       :string
    t.column "address",    :string
    t.column "city",       :string
    t.column "state",      :string
    t.column "zip",        :string
    t.column "created_by", :integer
  end

  create_table "liens", :force => true do |t|
    t.column "created_at",                   :datetime
    t.column "updated_at",                   :datetime
    t.column "patient_last",                 :string
    t.column "patient_first",                :string
    t.column "patient_address",              :string
    t.column "patient_city",                 :string
    t.column "patient_state",                :string
    t.column "patient_zip",                  :string
    t.column "patient_home",                 :string
    t.column "patient_cell",                 :string
    t.column "patient_attorney_name",        :string
    t.column "patient_attorney_address",     :string
    t.column "patient_attorney_city",        :string
    t.column "patient_attorney_state",       :string
    t.column "patient_attorney_zip",         :string
    t.column "patient_attorney_phone",       :string
    t.column "patient_attorney_fax",         :string
    t.column "patient_insurance_company",    :string
    t.column "patient_insurance_address",    :string
    t.column "patient_insurance_city",       :string
    t.column "patient_insurance_state",      :string
    t.column "patient_insurance_zip",        :string
    t.column "patient_insurance_adjuster",   :string
    t.column "patient_insurance_phone",      :string
    t.column "patient_insurance_ext",        :string
    t.column "patient_insurance_claim",      :string
    t.column "defendant_name",               :string
    t.column "defendant_address",            :string
    t.column "defendant_city",               :string
    t.column "defendant_state",              :string
    t.column "defendant_zip",                :string
    t.column "defendant_home",               :string
    t.column "defendant_cell",               :string
    t.column "defendant_insurance_company",  :string
    t.column "defendant_insurance_address",  :string
    t.column "defendant_insurance_city",     :string
    t.column "defendant_insurance_state",    :string
    t.column "defendant_insurance_zip",      :string
    t.column "defendant_insurance_adjuster", :string
    t.column "defendant_insurance_phone",    :string
    t.column "defendant_insurance_ext",      :string
    t.column "defendant_insurance_claim",    :string
    t.column "other_name",                   :string
    t.column "other_address",                :string
    t.column "other_city",                   :string
    t.column "other_state",                  :string
    t.column "other_zip",                    :string
    t.column "other_home",                   :string
    t.column "other_cell",                   :string
    t.column "other_insurance_company",      :string
    t.column "other_insurance_address",      :string
    t.column "other_insurance_city",         :string
    t.column "other_insurance_state",        :string
    t.column "other_insurance_zip",          :string
    t.column "other_insurance_adjuster",     :string
    t.column "other_insurance_phone",        :string
    t.column "other_insurance_ext",          :string
    t.column "other_insurance_claim",        :string
    t.column "case_accident_date",           :date
    t.column "case_filed_date",              :date
    t.column "case_release_date",            :date
    t.column "case_book",                    :string
    t.column "case_lien_number",             :string
    t.column "case_lien_amount",             :float
    t.column "case_collected_date",          :date
    t.column "case_page",                    :string
    t.column "case_amend_date",              :date
    t.column "case_amend_reason",            :text
    t.column "user_id",                      :integer
    t.column "case_status_not_final",        :boolean,  :default => false
    t.column "case_status_amended",          :boolean,  :default => false
    t.column "case_status_final",            :boolean,  :default => false
    t.column "letter_sent",                  :boolean,  :default => false
  end

  create_table "newadmins", :force => true do |t|
    t.column "name",              :string
    t.column "password",          :string
    t.column "crypted_password",  :string
    t.column "password_salt",     :string
    t.column "persistence_token", :string
    t.column "user_type",         :boolean
  end

  create_table "notes", :force => true do |t|
    t.column "body",       :text
    t.column "lien_id",    :integer
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "promocodes", :force => true do |t|
    t.column "name",    :string
    t.column "price",   :integer
    t.column "valid",   :datetime
    t.column "used",    :boolean
    t.column "user_id", :integer
  end

  create_table "providers", :force => true do |t|
    t.column "company",         :string
    t.column "category",        :string
    t.column "contact_name",    :string
    t.column "email",           :string
    t.column "address",         :string
    t.column "city",            :string
    t.column "state",           :string
    t.column "zip",             :string
    t.column "phone",           :string
    t.column "description",     :text
    t.column "start_date",      :date
    t.column "contract_length", :integer
    t.column "rate",            :string
    t.column "user_id",         :integer
    t.column "created_at",      :datetime
    t.column "updated_at",      :datetime
    t.column "category_id",     :integer
  end

  create_table "referrals", :force => true do |t|
    t.column "provider_id",                  :integer
    t.column "referrer_id",                  :integer
    t.column "patient_last",                 :string
    t.column "patient_first",                :string
    t.column "patient_address",              :string
    t.column "patient_city",                 :string
    t.column "patient_state",                :string
    t.column "patient_zip",                  :string
    t.column "patient_home",                 :string
    t.column "patient_cell",                 :string
    t.column "patient_attorney_name",        :string
    t.column "patient_attorney_address",     :string
    t.column "patient_attorney_city",        :string
    t.column "patient_attorney_state",       :string
    t.column "patient_attorney_zip",         :string
    t.column "patient_attorney_phone",       :string
    t.column "patient_attorney_fax",         :string
    t.column "patient_insurance_company",    :string
    t.column "patient_insurance_address",    :string
    t.column "patient_insurance_city",       :string
    t.column "patient_insurance_state",      :string
    t.column "patient_insurance_zip",        :string
    t.column "patient_insurance_adjuster",   :string
    t.column "patient_insurance_phone",      :string
    t.column "patient_insurance_ext",        :string
    t.column "patient_insurance_claim",      :string
    t.column "defendant_name",               :string
    t.column "defendant_address",            :string
    t.column "defendant_city",               :string
    t.column "defendant_state",              :string
    t.column "defendant_zip",                :string
    t.column "defendant_home",               :string
    t.column "defendant_cell",               :string
    t.column "defendant_insurance_company",  :string
    t.column "defendant_insurance_address",  :string
    t.column "defendant_insurance_city",     :string
    t.column "defendant_insurance_state",    :string
    t.column "defendant_insurance_zip",      :string
    t.column "defendant_insurance_adjuster", :string
    t.column "defendant_insurance_phone",    :string
    t.column "defendant_insurance_ext",      :string
    t.column "defendant_insurance_claim",    :string
    t.column "other_name",                   :string
    t.column "other_address",                :string
    t.column "other_city",                   :string
    t.column "other_state",                  :string
    t.column "other_zip",                    :string
    t.column "other_home",                   :string
    t.column "other_cell",                   :string
    t.column "other_insurance_company",      :string
    t.column "other_insurance_address",      :string
    t.column "other_insurance_city",         :string
    t.column "other_insurance_state",        :string
    t.column "other_insurance_zip",          :string
    t.column "other_insurance_adjuster",     :string
    t.column "other_insurance_phone",        :string
    t.column "other_insurance_ext",          :string
    t.column "other_insurance_claim",        :string
    t.column "case_accident_date",           :date
    t.column "added",                        :boolean,  :default => false
    t.column "deleted",                      :boolean,  :default => false
    t.column "created_at",                   :datetime
    t.column "updated_at",                   :datetime
    t.column "email",                        :string
    t.column "patient_insurance_name",       :string
    t.column "defendant_insurance_name",     :string
    t.column "other_insurance_name",         :string
  end

  create_table "roles", :force => true do |t|
    t.column "rolename", :string
  end

  create_table "schema_migrations", :id => false, :force => true do |t|
    t.column "version", :string, :null => false
  end

  add_index "schema_migrations", ["version"], :name => "unique_schema_migrations", :unique => true

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"
  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"

  create_table "users", :force => true do |t|
    t.column "login",                     :string
    t.column "password",                  :string
    t.column "physician_name",            :string
    t.column "email",                     :string
    t.column "clinic",                    :string
    t.column "address",                   :string
    t.column "city",                      :string
    t.column "state",                     :string
    t.column "zip",                       :string
    t.column "phone_area",                :string
    t.column "phone_prefix",              :string
    t.column "phone_suffix",              :string
    t.column "tax",                       :string
    t.column "payable",                   :string
    t.column "county",                    :string
    t.column "paper",                     :integer
    t.column "account",                   :integer
    t.column "newsletter",                :integer
    t.column "notary_name",               :string
    t.column "notary_county",             :string
    t.column "notary_commission",         :string
    t.column "notary_expires",            :date
    t.column "provider_id",               :integer
    t.column "reset_password_code",       :string
    t.column "reset_password_code_until", :datetime
    t.column "paid",                      :boolean,  :default => false
    t.column "subscribe_up_to",           :datetime
    t.column "role_id",                   :integer,  :default => 1
  end

end
